name: Clean Architecture CI
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:

jobs:
  #  lint:
  #    name: Lint Check
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Checkout the code
  #        uses: actions/checkout@v2
  #
  #      - name: Run Debug Lint
  #        run: ./gradlew lintDebug
  #
  #      - name: Upload html test report
  #        uses: actions/upload-artifact@v2
  #        with:
  #          name: lint.html
  #          path: app/build/reports/lint-results-debug.html
  #
  #  unit-test:
  #    needs: [ lint ]
  #    name: Unit Test
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Checkout the code
  #        uses: actions/checkout@v2
  #
  #      - name: Run unit Test
  #        run: echo Run Unit Test
  #
  #      - name: Run tests
  #        run: ./gradlew test
  #
  #      - name: Upload test report
  #        uses: actions/upload-artifact@v2
  #        with:
  #          name: unit_test_report
  #          path: app/build/reports/tests/testDebugUnitTest/
  package:
    #    needs: [ unit-test ]
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build & Upload On Firebase
        run: ./gradlew assembleDebug --stacktrace appDistributionUploadDebug
      with:
        appId: ${{ secrets.FIREBASE_APP_ID}}
        token: ${{ secrets.FIREBASE_TOKEN}}
        groups: testers
        file: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload On Github Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Debug-Demo.apk
          path: app/build/outputs/apk/debug/app-debug.apk